INSERT INTO REGISTRY (ID, NAME, BALANCE, CUSTOMER_ID) VALUES (1, 'Wallet', 1000.0, 1)
INSERT INTO REGISTRY (ID, NAME, BALANCE, CUSTOMER_ID) VALUES (2, 'Savings', 5000.0, 1)
INSERT INTO REGISTRY (ID, NAME, BALANCE, CUSTOMER_ID) VALUES (3, 'Insurance policy', 0.0, 1)
INSERT INTO REGISTRY (ID, NAME, BALANCE, CUSTOMER_ID) VALUES (4, 'Food expenses', 0.0, 1)