create table REGISTRY (ID integer not null, NAME varchar(255), BALANCE double, CUSTOMER_ID integer, primary key (ID))
create table CUSTOMER (ID integer not null, FIRST_NAME varchar(255), LAST_NAME varchar(255), primary key (ID))
create table TRANSFER (ID bigint not null GENERATED BY DEFAULT AS IDENTITY, SOURCE integer, AMOUNT double, DESTINATION integer, EXECUTION_DATE timestamp, primary key (ID))